# Generated by Django 5.2.4 on 2026-05-09 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Projet / Réalisation', 'verbose_name_plural': 'Projets / Réalisations'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Catégorie de Projet', 'verbose_name_plural': 'Catégories de Projets'},
        ),
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'verbose_name': 'Photo de galerie', 'verbose_name_plural': 'Photos de galerie'},
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, verbose_name="Client / Maître d'ouvrage"),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='duree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Durée du chantier'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Projet mis en avant'),
        ),
        migrations.AddField(
            model_name='project',
            name='metres_cables',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mètres de câbles'),
        ),
        migrations.AddField(
            model_name='project',
            name='nombre_points',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nombre de points d'éclairage"),
        ),
        migrations.AddField(
            model_name='project',
            name='puissance_installee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Puissance installée (kVA/kW)'),
        ),
        migrations.AddField(
            model_name='project',
            name='resultat',
            field=models.TextField(blank=True, verbose_name='Les Résultats'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('termine', 'Terminé'), ('livré', 'Livré')], default='termine', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='project',
            name='superficie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Superficie (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='temoignage_auteur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Auteur du témoignage'),
        ),
        migrations.AddField(
            model_name='project',
            name='temoignage_client',
            field=models.TextField(blank=True, verbose_name='Témoignage client'),
        ),
        migrations.AddField(
            model_name='project',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wilaya'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='icon',
            field=models.CharField(default='fas fa-bolt', max_length=100, verbose_name='Icône FontAwesome'),
        ),
        migrations.AddField(
            model_name='projectgallery',
            name='legende',
            field=models.CharField(blank=True, max_length=255, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, verbose_name='Le Défi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(upload_to='projects/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='products_used',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Produits utilisés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Notre Solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(verbose_name='Année de réalisation'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project', verbose_name='Projet'),
        ),
    ]
