# Generated by Django 5.2.4 on 2026-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonelgazMissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coupure', 'Coupure'), ('retablissement', 'Rétablissement'), ('branchements', 'Branchements'), ('detecteur_co', 'Détecteur de Monoxyde de Carbone'), ('changement_compteur', 'Changement de Compteur')], max_length=30, verbose_name='Catégorie de mission')),
                ('image', models.ImageField(upload_to='sonelgaz/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende (optionnel)')),
            ],
            options={
                'verbose_name': 'Image de mission Sonelgaz',
                'verbose_name_plural': 'Images de missions Sonelgaz',
                'ordering': ['category'],
            },
        ),
    ]
