# Generated by Django 5.2.4 on 2026-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(help_text='ex: Technicien supérieur', max_length=150, verbose_name='Poste')),
                ('address', models.CharField(help_text='ex: BIRTOUTA, ALGER', max_length=200, verbose_name='Adresse')),
                ('profile_photo', models.ImageField(upload_to='team/profiles/', verbose_name='Photo de profil')),
                ('experience', models.TextField(help_text='Saisissez une expérience par ligne (elles seront affichées sous forme de puces)', verbose_name='Expérience')),
                ('work_done', models.TextField(help_text='Saisissez un travail par ligne (elles seront affichées sous forme de puces)', verbose_name='Travaux réalisés')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/work/', verbose_name='Image de réalisation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='team.employee')),
            ],
            options={
                'verbose_name': 'Image de travail',
                'verbose_name_plural': 'Images de travaux',
            },
        ),
    ]
