# Generated by Django 5.2.4 on 2026-05-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(default='Équipe Technique Garoui', max_length=100, verbose_name='Auteur')),
                ('cover_image', models.ImageField(upload_to='blog/covers/', verbose_name='Image de couverture')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Extrait (résumé court)')),
                ('content', models.TextField(verbose_name="Contenu de l'article (Markdown ou HTML autorisé)")),
                ('is_published', models.BooleanField(default=True, verbose_name='Est publié ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
