# Generated by Django 5.2.4 on 2026-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / Promoteur")),
                ('nom_contact', models.CharField(max_length=150, verbose_name='Nom du contact')),
                ('poste_contact', models.CharField(blank=True, max_length=100, verbose_name='Poste / Fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya / Région')),
                ('secteur', models.CharField(choices=[('residentiel', 'Résidentiel (AADL, Villas, Cités)'), ('hospitalier', 'Hospitalier (Hôpitaux, Cliniques)'), ('touristique', 'Touristique & Tertiaire (Hôtels, Centres commerciaux)'), ('industriel', 'Industriel (Usines, Entrepôts)'), ('autre', 'Autre')], max_length=50, verbose_name="Secteur d'activité")),
                ('type_travaux', models.CharField(choices=[('courant_fort', 'Courant Fort (Puissance)'), ('courant_faible', 'Courant Faible (Données, Sécurité)'), ('domotique', 'Domotique & Smart Home'), ('maintenance', 'Maintenance & Diagnostic'), ('mixte', 'Projet Mixte (Plusieurs types)')], max_length=50, verbose_name='Type de travaux')),
                ('description_projet', models.TextField(verbose_name='Description détaillée du projet')),
                ('superficie', models.CharField(blank=True, max_length=100, verbose_name='Superficie approximative (m²)')),
                ('budget_estimatif', models.CharField(blank=True, max_length=100, verbose_name='Budget estimatif (facultatif)')),
                ('delai_souhaite', models.CharField(blank=True, max_length=100, verbose_name='Délai souhaité')),
                ('plan_architectural', models.FileField(blank=True, null=True, upload_to='devis/plans/', verbose_name='Plan architectural (PDF, DWG, DXF)')),
                ('cahier_des_charges', models.FileField(blank=True, null=True, upload_to='devis/cdc/', verbose_name='Cahier des charges (PDF)')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('devis_envoye', 'Devis envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Demande de Devis',
                'verbose_name_plural': 'Demandes de Devis',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
