# Generated by Django 5.2.4 on 2026-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ip_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='Indice de protection (IP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_pdf',
            field=models.FileField(blank=True, null=True, upload_to='products/specs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='wattage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='shop.certificate'),
        ),
    ]
