# Generated by Django 5.2.4 on 2026-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom complet / Contact')),
                ('company', models.CharField(max_length=255, verbose_name='Entreprise / Établissement')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('intervention_type', models.CharField(choices=[('panne_totale', 'Panne électrique totale'), ('panne_partielle', 'Panne partielle / Disfonctionnement'), ('maintenance', 'Maintenance préventive'), ('diagnostic', 'Diagnostic / Audit technique'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'intervention")),
                ('urgency', models.CharField(choices=[('basse', 'Basse (Planifiable)'), ('moyenne', 'Moyenne (Sous 48h-72h)'), ('haute', 'Haute (Sous 24h)'), ('critique', 'Critique (Arrêt de production - Immédiat)')], max_length=20, verbose_name="Niveau d'urgence")),
                ('equipment_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Équipement concerné (Optionnel)')),
                ('description', models.TextField(verbose_name='Description détaillée du problème')),
                ('address', models.TextField(verbose_name="Adresse d'intervention")),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('planifiee', 'Planifiée'), ('en_cours', "En cours d'intervention"), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-created_at'],
            },
        ),
    ]
